### ISSUE TITLE
Ability to get plain text of content piece.

### ISSUE THREAD

**Issue by kcoderhtml** [vriteio/vrite#16]
I want to get the raw data from `</Content>`. I have a reading time function in astro that needs the text of the article to be passed in as a string. This is an amazing framework for creating a blog. I've immediately switched over, and it is a breeze to work with.

**Comment by areknawo** [comment]
It's best to do it with Content Transformers. You can read more about them in the [SDK docs](https://docs.vrite.io/javascript-sdk) and check out the most up-to-date examples [in the repo](https://github.com/vriteio/vrite/tree/main/packages/sdk/javascript/src/transformers).

That said, for retrieving raw content you can create a transformer like so:

```typescript
const getRawText = async () => {
  const contentPiece = await client.contentPieces.get({ id: Astro.props.id, content: true });
  const rawTextTransformer = createContentTransformer({
    applyInlineFormatting(type, attrs, content) {
      return content;
    },
    transformNode(type, attrs, content) {
      if (type === "codeBlock") {
        return "";
      }

      return content;
    }
  });

  return rawTextTransformer(contentPiece.content);
};
```

The drawback is that this will fetch the JSON content again (in addition to `<Content/>` element). I'll have to update it to allow passing already-retrieved JSON content to the `<Content/>` element. I'll keep this issue open until I do so.

Hopefully, this answers your question.

**Comment by kcoderhtml** [comment]
Thanks that does!

**Comment by areknawo** [comment]
I've added the `content` prop to `<Content/>`. You can upgrade to v2023.6.26-beta of the `@vrite/sdk` and use it to get rid of duplicate data fetching. 🙂

**Comment by kcoderhtml** [comment]
Thanks! How would that be used?

**Comment by areknawo** [comment]
Fetch the content piece, together with the content at the top level, and then use it for getting raw text, using other metadata (if you need to), and passing the JSON content to `<Content/>` component instead of `<Content contentPieceId="..." />` you might have been doing previously.

```astro
---
// [slug].astro
const contentPiece = await client.contentPieces.get({ id: Astro.props.id, content: true });
const getRawText = () => {
  const rawTextTransformer = createContentTransformer({
    applyInlineFormatting(type, attrs, content) {
      return content;
    },
    transformNode(type, attrs, content) {
      if (type === "codeBlock") {
        return "";
      }

      return content;
    }
  });

  return rawTextTransformer(contentPiece.content);
};
---

<Content content={contentPiece.content} />
```

**Comment by kcoderhtml** [comment]
Okay, thanks, that's what I ended up doing. Probably not related, but after I updated the package, my Netlify dev server started failing with the below error:
```
02:20:47 PM [astro] update /.netlify/edge-functions-import-map.json
:20:47 PM [astro] update /.netlify/edge-functions-import-map.json (x2)
/Users/kierank/git/astro-site/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/fsevents/fsevents.js:13:23: ERROR: No loader is configured for ".node" files: node_modules/fsevents/fsevents.node
    at failureErrorWithLog (/Users/kierank/git/astro-site/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/kierank/git/astro-site/node_modules/esbuild/lib/main.js:1048:25
    at /Users/kierank/git/astro-site/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 23,
        file: 'node_modules/fsevents/fsevents.js',
        length: 17,
        line: 13,
        lineText: 'const Native = require("./fsevents.node");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No loader is configured for ".node" files: node_modules/fsevents/fsevents.node'
    }
  ],
  warnings: []
}

Node.js v20.2.0
◈ Command failed with exit code 1: npm run dev. Shutting down Netlify Dev server
```

**Comment by areknawo** [comment]
Maybe try removing the lock file and reinstalling all the node_modules.
Doesn't seem related to the update though. Only the Astro component was changed. Also, the Vrite blog works well: https://vrite.io/blog/

**Comment by kcoderhtml** [comment]
Okay! I was able to fix the issue by adding 
```mjs
vite: {
	optimizeDeps: { exclude: ["fsevents"] },
},
```
to the astro.config.mjs

**Comment by kcoderhtml** [comment]
<img width="781" alt="Screenshot 2023-06-26 at 2 41 01 PM" src="https://github.com/vriteio/vrite/assets/92754843/0d520ca2-bb43-46be-89cf-7eb64b7e08c7">
I did notice that while the new prop does work, it hasn't been recognized as a valid value yet.

**Comment by areknawo** [comment]
Sorry for that. Try v2023.6.26-beta.2 - types should be fixed.

**Comment by kcoderhtml** [comment]
The type for the `content` asks for a string, but when a string is passed, it fails to display anything and needs an object to be passed to it.

**Comment by areknawo** [comment]
It should be a `JSONContent` object. Should be fixed in v2023.6.26-beta.3.
Really sorry for this. It's difficult to properly test the types in general, and especially in this case, as they work a bit differently when published vs in the monorepo. I'll try to improve this later on.

**Comment by kcoderhtml** [comment]
No worries, this project is amazing and makes it so much easier to build a dev blog.

**Comment by kcoderhtml** [comment]
If there is anything I can do to help this project, I would be happy to help.

**Comment by areknawo** [comment]
Thanks! Hopefully, all works for you now and I've made it up to you with real-time support 😅

The easiest thing you can do is report any bugs and feature requests you might find/have. This helps a lot to get the project to the first stable release.

**Comment by kcoderhtml** [comment]
Okay. I will continue to do that.
