### ISSUE TITLE
Code blocks fail to display properly when under a numbered list

### ISSUE THREAD

**Issue by kcoderhtml** [vriteio/vrite#19]
When I have a code block that is inside a numbered list item than it will not be highlighted when rendered.

![image](https://github.com/vriteio/vrite/assets/92754843/b43587d9-3d20-4108-9057-72f4f0e5293f)
![image](https://github.com/vriteio/vrite/assets/92754843/99b5c58b-3e53-44e4-ae8d-1a090630eabc)

**Comment by areknawo** [comment]
The nested code blocks aren't properly converted to Astro highlighted `<Code>` components from standard `<pre>` blocks.

Thanks for reporting, will work on fixing this soon.

**Comment by areknawo** [comment]
Hey, sorry this took so long. This is fixed now in `@vrite/sdk@2023.7.13-beta`. Update and give it a try.
Feel free to reopen if there are any related issues.

**Comment by kcoderhtml** [comment]
No worries! I tested it and can confirm that it fixed my problem. Thank you!
