### ISSUE TITLE
Transitioning from link mode to plain text mode is quite challenging.

### ISSUE THREAD

**Issue by kcoderhtml** [vriteio/vrite#29]
It is quite hard when you type in a link or paste in a link to get back to writing text. The only way I have found to reliably get back is to copy a plain text space and paste it again at the end of the link.

**Comment by areknawo** [comment]
This is fixed in v2023.8.11-beta. There's now an empty space added after the link mark (just like other marks, i.e. bold, italic, etc.)

**Comment by kcoderhtml** [comment]
Thank you!
