### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [vriteio/vrite#31]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@coderbm1) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by areknawo** [comment]
Hi,
Thanks for reaching out! Vrite is still a relatively young project and I'm aware that it has room to improve - especially on the security front.

Following your recommendation I created a `SECURITY.md` file and a dedicated email address for any security reports. Please, send the details on the vulnerability to security@vrite.io.

Thanks!
