### ISSUE TITLE
Request to enable GitHub Private Vulnerability Reporting in vrite repository

### ISSUE THREAD

**Issue by lambdasawa** [vriteio/vrite#46]
Hello! Thank you for developing a great product.

I have found a security issue in vrite.
As a form of reporting this, I find GitHub's [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature useful.
However, this feature is disabled in vrite repository.

Is it possible to enable this feature?

Previously, I used to report issues via the huntr platform.
However, there was a recent update to huntr and it seems that repositories not directly related to AI/ML can no longer report issues via huntr.

**Comment by areknawo** [comment]
Hi,

Indeed, the Huntr update is bad news for non-AI projects using the platform.

I've enabled the reporting on GitHub. Will also update the `SECURITY.md` file in the coming days with further guidelines for testing and reporting vulnerabilities.

Thanks for your help and effort in reporting those - especially at these early stages of the project.

**Comment by lambdasawa** [comment]
Thank you for your response :smile:
I was able to submit my report successfully.
