### ISSUE TITLE
Captions for images

### ISSUE THREAD

**Issue by kcoderhtml** [vriteio/vrite#49]
Adding captions for images would be useful especially for copywrite considerations. Here is how I accomplish that for static images on my site.
```html
<picture>
  <img
    src="/assets/image.png"
    alt="Test Image"
  />
  <figcaption>Test image by kieran klukas</figcaption>
</picture>
```

**Comment by areknawo** [comment]
Added the `caption` attribute to image nodes in v0.4.
Support for it in the content transformers might come later on (now checking if using `<picture>` wrapping instead of direct `<img>` won't cause any issues on supported platforms)
