### ISSUE TITLE
docs: unclear how to add rich content via api

### ISSUE THREAD

**Issue by kcoderhtml** [vriteio/vrite#58]
I would like to provide an image via the api to be included in a post but when passed via Markdown it isn't parsed. How are you supposed to add rich content to the page?

**Comment by areknawo** [comment]
The `content` property in `POST /content-pieces` and `PUT /content-pieces` should be a "clean" (just describing the content formatting) HTML string. You can use `gfmInputTransformer` from the SDK to get one from your Markdown string.

**Comment by kcoderhtml** [comment]
Thanks!

**Comment by areknawo** [comment]
Great. Will keep this open as I'm working on improving the docs now.

**Comment by areknawo** [comment]
v0.4.1 has new, dedicated API docs: https://docs.vrite.io/api/authentication/. It should make details like this a bit clearer. Working on better docs and other improvements for SDKs next.
