### ISSUE TITLE
Fix Error: Select element extension in editor

### ISSUE THREAD

**Issue by vuthanhbayit** [vriteio/vrite#63]
Hi vrite

When I select to `Element extension`, I get an Error like image below

![image](https://github.com/vriteio/vrite/assets/37856246/04ebb107-e1b5-4de5-936f-02e7287d3023)

**Comment by areknawo** [comment]
@vuthanhbayit Should be fixed on the cloud now. For self-hosting, I will release a new image likely next week.

Also, FYI, there's `<[ELEMENT_NAME]>` (or `<[ELEMENT_NAME]/>`) shortcut you can use to insert elements.
