### ISSUE TITLE
Bug: Setting source control transformer to mdx sets it back to markdown

### ISSUE THREAD

**Issue by JorgeAtPaladin** [vriteio/vrite#67]
When I try to connect my git repository with mdx content, this content can't be loaded:

![Capture d’écran 2024-04-30 à 12 15 33](https://github.com/vriteio/vrite/assets/87263486/2af676e1-8bcb-4438-9ed1-50902c6247d0)

![Capture d’écran 2024-04-30 à 12 16 30](https://github.com/vriteio/vrite/assets/87263486/c16d2653-6f70-428a-9b4f-6cb1d63ffd60)

Once I press `save`:

![Capture d’écran 2024-04-30 à 12 16 47](https://github.com/vriteio/vrite/assets/87263486/c25e848b-ca82-4a30-9132-90e287d104a0)

(Notice a separate bug where the editor view infinitely loads now, not sure why that is)

Pressing `sync now`:

![Capture d’écran 2024-04-30 à 12 17 28](https://github.com/vriteio/vrite/assets/87263486/c2cb5fb7-ecab-44ae-871f-877d95547381)

Says latest changes synced in the bottom right (already gone) in green and shows this. View of settings by pressing the github logo:

![Capture d’écran 2024-04-30 à 12 17 52](https://github.com/vriteio/vrite/assets/87263486/e3ce331e-240d-4ce5-87a5-1029656b616d)

Notice the `markdown` transformer... I have the mdx extension, which is apparent as I could select it.

**Comment by JorgeAtPaladin** [comment]
Pressing `pull` also says, "couldn't pull changes"

**Comment by areknawo** [comment]
The proper transformer was configured. The only issue was a wrong label being displayed. This should be fixed now.

For the pull issue/comment - I don't have enough details to debug/fix whatever it was.
If you encounter it again, please report it in a separate issue.
