### ISSUE TITLE
Bug: Importing a table from MDX-based source-control renders it as text.

### ISSUE THREAD

**Issue by JorgeAtPaladin** [vriteio/vrite#68]
![Capture d’écran 2024-04-30 à 12 44 57](https://github.com/vriteio/vrite/assets/87263486/3e016dfd-8ad4-4331-b01f-426af00e56b3)

If I make a change to an mdx table within github, eg. change some text, and then re-sync the file to vrite by pressing `pull`, the table is no longer loaded as a table.

It may be sensible to store the tables in hypertext within mdx? not sure how to fix this, storing tables as .md tables is always going to be a bit lossfull as well.

**environment**: This table is present within a custom element view.

**Comment by areknawo** [comment]
This should be fixed now. Please check and reopen the issue if you experience this with your content again.
