### ISSUE TITLE
Link invalid when testing invitation

### ISSUE THREAD

**Issue by almereyda** [vriteio/vrite#71]
When testing locally, emails and logins work.

But invite links pasted into a private browser window which has a second user already authenticated fail with:

> ## Link invalid
> Workspace invite

![grafik](https://github.com/vriteio/vrite/assets/1645308/b22f7f92-44a1-45da-b257-512ed8eb4dc4)

**Comment by areknawo** [comment]
Fixed this issue a few days ago on Vrite Cloud.
Will make a new self-hosting release with the fix soon.

**Comment by areknawo** [comment]
Update to `v0.4.2` and let me know if the issue you've experienced is fixed.

**Comment by almereyda** [comment]
Confirmed.
