### ISSUE TITLE
JS SDK depends on Astro: 27 MB

### ISSUE THREAD

**Issue by tbeseda** [vriteio/vrite#8]
I'm enjoying Vrite! Just wanted to alert you to a roadblock I had for adopting the SDK:

I'd like to use the SDK in a Lambda function but I hesitate to install `@vrite/sdk` since it has a 27.5 MB dependency. Just having that on disk (even if the code path never loads it) will add to my function's cold start considerably. I'm not likely to add a build step to treeshake what is otherwise a really simple Lambda.

Is there a way the references to Astro in the Vrite SDK could use a sub-dependency of `astro`? I haven't looked at their available modules in a while, so I'm unsure. I think Astro is large because they're distributing WASM

In the mean time I can use `fetch`. Thanks for the Swagger docs, they're helpful 👍

**Comment by areknawo** [comment]
That’s a fair point. I'll try moving Astro to peer dependencies. It should help.

**Comment by areknawo** [comment]
`astro` is now an optional peer-dependency of `@vrite/sdk`. Try installing the latest version - the *node_modules* should be much smaller.

**Comment by tbeseda** [comment]
Awesome, vrite's SDK is now one of the smallest dependencies in this Lambda. Thanks @areknawo
